version: '3.7'
services:
  hub-postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "hizonelite"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"